FROM node:alpine as builder
WORKDIR /app
COPY package.json yarn.lock ./
RUN ["yarn", "install"]

FROM node:alpine
WORKDIR /app
COPY --from=builder /app/node_modules node_modules
EXPOSE 3000
CMD ["yarn", "start"]
COPY . .
